
import React, { useState, useEffect } from 'react';
import { User, Building, Bell, Save, CreditCard, Shield, CheckCircle2, Zap, Smartphone, Mail, Lock, History, Monitor, Upload, AlertCircle, Users, Plus, Trash2, Plug } from 'lucide-react';
import { Button, Card, CardContent, Input, PageHeader, CardHeader, CardTitle, Badge, YouTubeConnectButton } from '../components/Common';
import { Role } from '../types';
import { MOCK_USERS } from '../mockData';
import { useI18n } from '../contexts/I18nContext';
import { useCurrency } from '../contexts/CurrencyContext';
import { navigateTo } from '../utils/navigation';
import { TrustBadgeGroup } from '../components/Trust';

// --- SUB-COMPONENTS ---

const ProfileSettings = ({ user, onSave, role }: { user: any, onSave: () => void, role: Role }) => {
  const { t } = useI18n();
  const [isSaving, setIsSaving] = useState(false);

  const handleSave = () => {
    setIsSaving(true);
    setTimeout(() => {
        setIsSaving(false);
        onSave();
    }, 1200);
  };

  return (
    <Card>
      <CardHeader><CardTitle>{t('settings.profile.title')}</CardTitle></CardHeader>
      <CardContent className="space-y-6">
        <div className="flex flex-col md:flex-row items-center md:items-start gap-6">
            <div className="relative group">
                <img src={user.avatarUrl} className="w-24 h-24 rounded-full border-4 border-slate-100 dark:border-slate-800 shadow-sm object-cover" />
                <button className="absolute bottom-0 right-0 bg-indigo-600 text-white p-1.5 rounded-full hover:bg-indigo-500 transition-colors shadow-sm">
                    <Upload size={14} />
                </button>
            </div>
            <div className="flex-1 space-y-4 w-full">
               <div className="space-y-2">
                  <h4 className="text-sm font-bold text-slate-900 dark:text-white uppercase tracking-wider">Account Status</h4>
                  {role === 'community' ? (
                     <TrustBadgeGroup badges={['identity', 'ownership']} />
                  ) : (
                     <TrustBadgeGroup badges={['identity', 'payment']} />
                  )}
               </div>
               <p className="text-sm text-slate-500 dark:text-slate-400">
                  Member since {new Date(user.createdAt || Date.now()).toLocaleDateString()}
               </p>
            </div>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Input label={t('settings.profile.full_name')} defaultValue={user.name} />
            <Input label={t('settings.profile.email')} defaultValue={user.email} />
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Input label="Job Title" defaultValue="Marketing Manager" />
            <Input label="Phone" defaultValue="+55 11 99999-9999" />
        </div>
        <div className="pt-2 border-t border-slate-100 dark:border-slate-800 flex justify-end">
            <Button icon={<Save size={18} />} onClick={handleSave} isLoading={isSaving}>{t('common.save')}</Button>
        </div>
      </CardContent>
    </Card>
  );
};

const CompanySettings = ({ role, onSave }: { role: Role, onSave: () => void }) => {
    const { t } = useI18n();
    const [isSaving, setIsSaving] = useState(false);

    const handleSave = () => {
        setIsSaving(true);
        setTimeout(() => {
            setIsSaving(false);
            onSave();
        }, 1200);
    };

    return (
        <div className="space-y-6">
            <Card>
                <CardHeader>
                    <div className="flex justify-between items-center">
                        <CardTitle>{role === 'brand' ? 'Business Details' : 'Detalhes do Canal'}</CardTitle>
                        <Badge variant="success">Active</Badge>
                    </div>
                </CardHeader>
                <CardContent className="space-y-6">
                    <div className="bg-slate-50 dark:bg-slate-900/50 p-4 rounded-xl border border-slate-200 dark:border-slate-800 flex items-start gap-3">
                        <AlertCircle className="text-indigo-500 mt-0.5" size={20} />
                        <div>
                            <p className="text-sm font-bold text-slate-900 dark:text-white">Legal Information</p>
                            <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
                                This information will appear on invoices and contracts generated by the platform.
                            </p>
                        </div>
                    </div>

                    <div className="grid grid-cols-1 gap-4">
                        <Input label="Legal Name / Razão Social" placeholder="e.g. TechStart Ltda" defaultValue="TechStart Ltda" />
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <Input label="Tax ID (CNPJ/VAT)" placeholder="00.000.000/0001-00" defaultValue="12.345.678/0001-90" />
                            <Input label="Website" placeholder="https://..." defaultValue="https://techstart.com" />
                        </div>
                    </div>

                    <div className="border-t border-slate-100 dark:border-slate-800 pt-4">
                        <h4 className="text-xs font-bold text-slate-500 uppercase mb-4">Address</h4>
                        <div className="grid grid-cols-1 gap-4">
                            <Input label="Street Address" defaultValue="Av. Paulista, 1000" />
                            <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                                <Input label="City" defaultValue="São Paulo" />
                                <Input label="State/Province" defaultValue="SP" />
                                <Input label="Zip/Postal Code" defaultValue="01310-100" />
                            </div>
                        </div>
                    </div>

                    <div className="pt-2 flex justify-end">
                        <Button icon={<Save size={18} />} onClick={handleSave} isLoading={isSaving}>{t('common.save')}</Button>
                    </div>
                </CardContent>
            </Card>

            <Card>
                <CardHeader><CardTitle>Public Presence</CardTitle></CardHeader>
                <CardContent>
                    <div className="flex items-center justify-between">
                        <div>
                            <p className="text-sm font-medium text-slate-900 dark:text-white">Storefront Configuration</p>
                            <p className="text-xs text-slate-500 mt-1">Manage how your {role === 'brand' ? 'brand portal' : 'media kit'} looks to partners.</p>
                        </div>
                        <Button variant="outline" onClick={() => navigateTo('/app/storefront')}>Edit Storefront</Button>
                    </div>
                </CardContent>
            </Card>
        </div>
    );
};

const TeamSettings = () => {
  const members = [
    { name: 'Alice Brand', email: 'alice@tech.com', role: 'Admin', status: 'Active' },
    { name: 'John Doe', email: 'john@tech.com', role: 'Editor', status: 'Active' },
    { name: 'Sarah Smith', email: 'sarah@tech.com', role: 'Viewer', status: 'Pending' },
  ];

  return (
    <Card>
      <CardHeader>
        <div className="flex justify-between items-center">
          <CardTitle>Team Members</CardTitle>
          <Button size="sm" icon={<Plus size={16} />}>Invite Member</Button>
        </div>
      </CardHeader>
      <CardContent>
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm">
            <thead className="bg-slate-50 dark:bg-slate-900 border-b border-slate-200 dark:border-slate-800 text-slate-500">
              <tr>
                <th className="p-3 font-medium">Name</th>
                <th className="p-3 font-medium">Role</th>
                <th className="p-3 font-medium">Status</th>
                <th className="p-3 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
              {members.map((m, i) => (
                <tr key={i} className="hover:bg-slate-50 dark:hover:bg-slate-900/50 transition-colors">
                  <td className="p-3">
                    <div className="font-medium text-slate-900 dark:text-white">{m.name}</div>
                    <div className="text-xs text-slate-500">{m.email}</div>
                  </td>
                  <td className="p-3 text-slate-600 dark:text-slate-400">{m.role}</td>
                  <td className="p-3">
                    <Badge variant={m.status === 'Active' ? 'success' : 'warning'}>{m.status}</Badge>
                  </td>
                  <td className="p-3 text-right">
                    <button className="text-slate-400 hover:text-rose-500 transition-colors"><Trash2 size={16} /></button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </CardContent>
    </Card>
  );
};

const IntegrationsSettings = ({ role }: { role: Role }) => {
  return (
    <div className="space-y-6">
      <Card>
        <CardHeader><CardTitle>Connected Platforms</CardTitle></CardHeader>
        <CardContent className="space-y-6">
          <div className="bg-slate-50 dark:bg-slate-900/50 border border-slate-200 dark:border-slate-800 rounded-xl p-6">
             <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
               <div>
                 <h3 className="text-lg font-bold text-slate-900 dark:text-white mb-1">YouTube</h3>
                 <p className="text-sm text-slate-500 dark:text-slate-400 max-w-lg">
                   Connect your YouTube channel to import analytics (subscribers, views, demographics). 
                   This verifies your identity and boosts your Trust Score.
                 </p>
               </div>
               <YouTubeConnectButton />
             </div>
          </div>

          {/* Placeholder for other integrations */}
          <div className="flex items-center justify-between p-4 border border-slate-200 dark:border-slate-800 rounded-xl opacity-60 grayscale">
             <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-slate-100 dark:bg-slate-800 rounded-lg flex items-center justify-center font-bold text-slate-500">IG</div>
                <div>
                   <p className="font-bold text-slate-700 dark:text-slate-300">Instagram</p>
                   <p className="text-xs text-slate-500">Coming soon</p>
                </div>
             </div>
             <Button variant="secondary" disabled size="sm">Connect</Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

const BillingSettings = ({ role }: { role: Role }) => {
  const { formatCurrency } = useCurrency();
  
  return (
    <div className="space-y-6">
        {/* PREMIUM PLAN CARD */}
        <div className="rounded-2xl overflow-hidden bg-gradient-to-r from-slate-900 to-indigo-950 border border-indigo-500/30 shadow-2xl relative">
            <div className="absolute top-0 right-0 w-64 h-64 bg-indigo-500/10 rounded-full blur-3xl -translate-y-1/2 translate-x-1/2 pointer-events-none"></div>
            <div className="p-8 relative z-10 flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
                <div>
                    <div className="flex items-center gap-3 mb-2">
                        <Badge variant="brand" className="bg-indigo-500 text-white border-transparent px-3">Growth Plan</Badge>
                        <span className="text-indigo-300 text-sm font-medium">Active</span>
                    </div>
                    <div className="flex items-baseline gap-2 mb-2">
                        <h2 className="text-4xl font-bold text-white">{formatCurrency(499)}</h2>
                        <span className="text-slate-400">/ month</span>
                    </div>
                    <p className="text-slate-400 text-sm">Next billing date: <span className="text-white font-medium">Oct 25, 2024</span></p>
                </div>
                <div className="flex gap-3">
                    <Button variant="secondary" className="bg-white/10 text-white border-white/20 hover:bg-white/20">Manage Plan</Button>
                    <Button className="bg-white text-indigo-900 hover:bg-indigo-50 shadow-xl shadow-indigo-900/50 border-transparent">Upgrade to Enterprise</Button>
                </div>
            </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Card>
                <CardHeader><CardTitle>Payment Method</CardTitle></CardHeader>
                <CardContent>
                    <div className="flex items-center justify-between p-4 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl mb-4">
                        <div className="flex items-center gap-3">
                            <div className="w-10 h-10 bg-white dark:bg-slate-800 rounded border border-slate-200 dark:border-slate-700 flex items-center justify-center">
                                <CreditCard size={20} className="text-slate-600 dark:text-slate-400" />
                            </div>
                            <div>
                                <p className="text-sm font-bold text-slate-900 dark:text-white">Mastercard ending in 4242</p>
                                <p className="text-xs text-slate-500">Expires 12/2025</p>
                            </div>
                        </div>
                        <Badge variant="success">Default</Badge>
                    </div>
                    <Button variant="outline" size="sm" icon={<CreditCard size={14} />}>Add Payment Method</Button>
                </CardContent>
            </Card>

            <Card>
                <CardHeader><CardTitle>Billing History</CardTitle></CardHeader>
                <CardContent className="p-0">
                    <div className="divide-y divide-slate-100 dark:divide-slate-800">
                        {[
                            { date: 'Sep 25, 2024', amount: 499, status: 'Paid', invoice: '#INV-2024-001' },
                            { date: 'Aug 25, 2024', amount: 499, status: 'Paid', invoice: '#INV-2024-002' },
                            { date: 'Jul 25, 2024', amount: 499, status: 'Paid', invoice: '#INV-2024-003' },
                        ].map((inv, i) => (
                            <div key={i} className="flex items-center justify-between p-4 hover:bg-slate-50 dark:hover:bg-slate-900/50 transition-colors">
                                <div>
                                    <p className="text-sm font-medium text-slate-900 dark:text-white">{inv.date}</p>
                                    <p className="text-xs text-slate-500">{inv.invoice}</p>
                                </div>
                                <div className="text-right">
                                    <p className="text-sm font-bold text-slate-900 dark:text-white">{formatCurrency(inv.amount)}</p>
                                    <span className="text-[10px] text-emerald-600 font-bold uppercase">{inv.status}</span>
                                </div>
                            </div>
                        ))}
                    </div>
                    <div className="p-4 border-t border-slate-100 dark:border-slate-800 text-center">
                        <button onClick={() => navigateTo('/app/payments')} className="text-sm text-indigo-600 hover:text-indigo-700 font-medium">View All Transactions</button>
                    </div>
                </CardContent>
            </Card>
        </div>
    </div>
  );
};

const NotificationSettings = () => {
  const [toggles, setToggles] = useState({
    email_marketing: true,
    email_security: true,
    push_messages: true,
    push_updates: false
  });

  const toggle = (key: keyof typeof toggles) => {
    setToggles(prev => ({ ...prev, [key]: !prev[key] }));
  };

  return (
    <Card>
      <CardHeader><CardTitle>Notification Preferences</CardTitle></CardHeader>
      <CardContent className="space-y-6">
        <div>
            <h4 className="text-sm font-bold text-slate-900 dark:text-white flex items-center gap-2 mb-3">
                <Mail size={16} className="text-slate-400" /> Email Notifications
            </h4>
            <div className="space-y-3">
                <div className="flex items-center justify-between p-3 bg-slate-50 dark:bg-slate-900 rounded-lg border border-slate-100 dark:border-slate-800">
                    <div>
                        <p className="text-sm font-medium text-slate-700 dark:text-slate-300">Marketing & Updates</p>
                        <p className="text-xs text-slate-500">Receive news about product features.</p>
                    </div>
                    <input type="checkbox" checked={toggles.email_marketing} onChange={() => toggle('email_marketing')} className="w-5 h-5 text-indigo-600 rounded" />
                </div>
                <div className="flex items-center justify-between p-3 bg-slate-50 dark:bg-slate-900 rounded-lg border border-slate-100 dark:border-slate-800">
                    <div>
                        <p className="text-sm font-medium text-slate-700 dark:text-slate-300">Security Alerts</p>
                        <p className="text-xs text-slate-500">Important account security notices.</p>
                    </div>
                    <input type="checkbox" checked={toggles.email_security} onChange={() => toggle('email_security')} disabled className="w-5 h-5 text-indigo-600 rounded opacity-50 cursor-not-allowed" />
                </div>
            </div>
        </div>

        <div>
            <h4 className="text-sm font-bold text-slate-900 dark:text-white flex items-center gap-2 mb-3">
                <Smartphone size={16} className="text-slate-400" /> Push Notifications
            </h4>
            <div className="space-y-3">
                <div className="flex items-center justify-between p-3 bg-slate-50 dark:bg-slate-900 rounded-lg border border-slate-100 dark:border-slate-800">
                    <div>
                        <p className="text-sm font-medium text-slate-700 dark:text-slate-300">Direct Messages</p>
                        <p className="text-xs text-slate-500">When partners send you a message.</p>
                    </div>
                    <input type="checkbox" checked={toggles.push_messages} onChange={() => toggle('push_messages')} className="w-5 h-5 text-indigo-600 rounded" />
                </div>
                <div className="flex items-center justify-between p-3 bg-slate-50 dark:bg-slate-900 rounded-lg border border-slate-100 dark:border-slate-800">
                    <div>
                        <p className="text-sm font-medium text-slate-700 dark:text-slate-300">Campaign Updates</p>
                        <p className="text-xs text-slate-500">Status changes on your campaigns.</p>
                    </div>
                    <input type="checkbox" checked={toggles.push_updates} onChange={() => toggle('push_updates')} className="w-5 h-5 text-indigo-600 rounded" />
                </div>
            </div>
        </div>
      </CardContent>
    </Card>
  );
};

const SecuritySettings = () => {
  return (
    <div className="space-y-6">
        <Card>
            <CardHeader><CardTitle>Login & Security</CardTitle></CardHeader>
            <CardContent className="space-y-6">
                <div className="flex justify-between items-center pb-6 border-b border-slate-100 dark:border-slate-800">
                    <div>
                        <p className="text-sm font-bold text-slate-900 dark:text-white">Password</p>
                        <p className="text-xs text-slate-500">Last changed 3 months ago</p>
                    </div>
                    <Button variant="outline" size="sm">Change Password</Button>
                </div>
                <div className="flex justify-between items-center">
                    <div>
                        <p className="text-sm font-bold text-slate-900 dark:text-white">Two-Factor Authentication (2FA)</p>
                        <p className="text-xs text-slate-500">Add an extra layer of security to your account.</p>
                    </div>
                    <div className="flex items-center gap-2">
                        <span className="text-xs text-slate-400 uppercase font-bold tracking-wider">Off</span>
                        <Button size="sm" variant="secondary">Enable</Button>
                    </div>
                </div>
            </CardContent>
        </Card>

        <Card>
            <CardHeader><CardTitle>Active Sessions</CardTitle></CardHeader>
            <CardContent>
                <div className="space-y-4">
                    <div className="flex items-start gap-4">
                        <div className="p-2 bg-emerald-100 dark:bg-emerald-900/30 rounded text-emerald-600 dark:text-emerald-400">
                            <Monitor size={20} />
                        </div>
                        <div className="flex-1">
                            <p className="text-sm font-bold text-slate-900 dark:text-white">Macbook Pro - Chrome</p>
                            <p className="text-xs text-slate-500">São Paulo, Brasil • Active now</p>
                        </div>
                        <Badge variant="success">Current</Badge>
                    </div>
                    <div className="flex items-start gap-4">
                        <div className="p-2 bg-slate-100 dark:bg-slate-800 rounded text-slate-500">
                            <Smartphone size={20} />
                        </div>
                        <div className="flex-1">
                            <p className="text-sm font-bold text-slate-900 dark:text-white">iPhone 13 - App</p>
                            <p className="text-xs text-slate-500">São Paulo, Brasil • 2 days ago</p>
                        </div>
                        <Button variant="ghost" size="xs" className="text-rose-500 hover:bg-rose-50">Revoke</Button>
                    </div>
                </div>
            </CardContent>
        </Card>

        {/* DANGER ZONE */}
        <div className="pt-6 mt-6 border-t border-slate-200 dark:border-slate-800">
            <h4 className="text-sm font-bold text-rose-600 dark:text-rose-500 mb-4">Danger Zone</h4>
            <div className="p-4 border border-rose-200 dark:border-rose-900/30 bg-rose-50 dark:bg-rose-900/10 rounded-xl flex items-center justify-between">
               <div>
                  <p className="text-sm font-medium text-slate-900 dark:text-white">Delete Account</p>
                  <p className="text-xs text-slate-500">Permanently remove your account and all data.</p>
               </div>
               <Button variant="danger" size="sm">Delete Account</Button>
            </div>
        </div>
    </div>
  );
};

// --- MAIN PAGE ---

export default function Settings({ userRole }: { userRole: Role }) {
  const { t } = useI18n();
  const [activeTab, setActiveTab] = useState('profile');
  const user = MOCK_USERS[0]; 

  // Sync tab with URL
  useEffect(() => {
    const path = window.location.pathname;
    const parts = path.split('/');
    // Check if the last part corresponds to a valid tab
    const lastPart = parts[parts.length - 1];
    if (['profile', 'billing', 'notifications', 'security', 'company', 'team', 'integrations'].includes(lastPart)) {
        setActiveTab(lastPart);
    } else {
        // If just /app/settings, default to profile
        setActiveTab('profile');
    }
  }, []);

  const handleTabChange = (tabId: string) => {
      setActiveTab(tabId);
      navigateTo(`/app/settings/${tabId}`);
  };

  const tabs = [
    { id: 'profile', label: t('settings.tabs.profile'), icon: User },
    { id: 'company', label: t('settings.tabs.company'), icon: Building },
    { id: 'integrations', label: 'Integrations', icon: Plug },
    { id: 'team', label: 'Team Members', icon: Users },
    { id: 'billing', label: 'Billing & Plan', icon: CreditCard },
    { id: 'notifications', label: t('settings.tabs.notifications'), icon: Bell },
    { id: 'security', label: 'Security', icon: Shield },
  ];

  return (
    <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
      <PageHeader title={t('settings.title')} subtitle={t('settings.subtitle')} />
      
      <div className="flex flex-col lg:flex-row gap-8">
         <div className="w-full lg:w-64 shrink-0 space-y-2">
            {tabs.map(tab => (
               <button
                  key={tab.id}
                  onClick={() => handleTabChange(tab.id)}
                  className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-medium transition-all duration-200 ${
                     activeTab === tab.id 
                     ? 'bg-white dark:bg-slate-900 text-indigo-600 dark:text-white shadow-md shadow-slate-200/50 dark:shadow-none border border-slate-100 dark:border-slate-800' 
                     : 'text-slate-500 hover:text-slate-900 dark:text-slate-400 dark:hover:text-white hover:bg-slate-100 dark:hover:bg-slate-800/50'
                  }`}
               >
                  <tab.icon size={18} className={activeTab === tab.id ? 'text-indigo-600 dark:text-indigo-400' : 'opacity-70'} />
                  {tab.label}
               </button>
            ))}
         </div>

         <div className="flex-1 min-w-0">
            {activeTab === 'profile' && (
                <ProfileSettings user={user} onSave={() => alert(t('settings.profile.save_success'))} role={userRole} />
            )}
            {activeTab === 'billing' && (
                <BillingSettings role={userRole} />
            )}
            {activeTab === 'notifications' && (
                <NotificationSettings />
            )}
            {activeTab === 'security' && (
                <SecuritySettings />
            )}
            {activeTab === 'company' && (
                <CompanySettings role={userRole} onSave={() => alert(t('settings.profile.save_success'))} />
            )}
            {activeTab === 'team' && (
                <TeamSettings />
            )}
            {activeTab === 'integrations' && (
                <IntegrationsSettings role={userRole} />
            )}
         </div>
      </div>
    </div>
  );
}
